In [6]:
import psycopg2 as psy
import pandas.io.sql as psql

In [7]:
con = psy.connect(host="192.168.0.10", dbname="test", user="test", password="test")

In [8]:
query = psql.read_sql("select pid, datname, usename , application_name, client_addr, state, query_start, query from pg_catalog.pg_stat_activity limit 10;", con)

In [9]:
query

,pid,datname,usename,application_name,client_addr,state,query_start,query
0,977,None,None,,None,None,NaT,
1,979,None,postgres,,None,None,NaT,
2,4556,test,test,DBeaver 7.2.0 - Main <postgres>,127.0.0.1,idle,2020-09-11 21:52:33.541429+00:00,SHOW search_path
3,3764,postgres,test,DBeaver 7.2.0 - Metadata <postgres>,127.0.0.1,idle,2020-09-11 21:43:55.094461+00:00,"SELECT t.oid,t.*,c.relkind,format_type(nullif(..."
4,3766,test,test,DBeaver 7.2.0 - SQLEditor <Script.sql>,127.0.0.1,idle,2020-09-11 21:52:55.881626+00:00,SHOW search_path
5,3768,test,test,DBeaver 7.2.0 - Main <test>,127.0.0.1,idle,2020-09-11 21:43:55.169541+00:00,SHOW search_path
6,3770,test,test,DBeaver 7.2.0 - Metadata <test>,127.0.0.1,idle,2020-09-11 21:52:47.421761+00:00,"SELECT t.oid,t.*,c.relkind,format_type(nullif(..."
7,9136,test,test,,192.168.0.10,idle,NaT,
8,9179,test,test,,192.168.0.10,active,2020-09-11 22:43:02.115251+00:00,"select pid, datname, usename , application_nam..."
9,975,None,None,,None,None,NaT,